fun      = @(x) x.*exp(-x.*x)-sin(x);
Dfun     = @(x) exp(-x.^2) - 2.*x.^2*exp(-x.^2) - cos(x);
x0       = -4;
%tol      = 1e-50;
%max_iter = 100;
%verbose  = 'iter';
NS = newton_class();
NS.set_tolerance( 1e-100 );
x = NS.solve( fun, Dfun, x0 );
fprintf('x = %g\n',x);
