addpath('../lib');
addpath('../maps');
addpath('../functions');

funTest1 = BoxThreeDimensionalFunction( 10 );

%%

fprintf('\n\n == Box Three Dimensional Fuction Test == \n\n')

LM1 = MinimizationLevembergMarquardt( funTest1 );
LM1.save_iterate_on();
LM1.setTolerance(1e-6);
LM1.setEpsilon2(1e-10);
LM1.setTau(1e-10);
LM1.setMaxIteration(int32(100));

x0 = funTest1.guesses;

[x_star,converged] = LM1.minimize(x0); % Minimization

x_ex  = funTest1.exact_solutions; % Extract exact solutions
x_set = funTest1.exact_linear_set;

fprintf('\nMinimum found, it is:      x = [ %2.2g %2.2g %2.2g ]''\n', x_star(1),x_star(2),x_star(3) );
fprintf('\nExact solutions were:      x = [ %2.2g %2.2g %2.2g ]'''  , x_ex(1,1),x_ex(2,1),x_ex(3,1) );
fprintf('\n                           x = [ %2.2g %2.2g %2.2g ]'''  , x_ex(1,2),x_ex(2,2),x_ex(3,2) );
fprintf('\nand the space generated by v = [ %2.2g %2.2g %2.2g ]''\n', x_set(1), x_set(2), x_set(3) );
