
% TEST LM ND

addpath(genpath('../lib'));
addpath(genpath('../functions'));

funTest1 = BoxThreeDimensionalFunction( 10 );

%%

fprintf(1,'\n\n == Box Three Dimensional Fuction Test == \n\n')

LM1    = MinimizationLM( funTest1 );

LM1.debug_on;

LM1.setTolerance(1e-6);
LM1.setEpsilon2(1e-10);

LM1.setTau(1e-10);
LM1.setMaxIteration(int32(100));

x0 = funTest1.guesses;

[x_star,converged] = LM1.minimize(x0); % Minimization

x_ex = funTest1.exact_solutions; % Extract exact solutions
x_set = funTest1.exact_linear_set;

fprintf(1,'\nMinimum found, it is:      x = [ %2.2g %2.2g %2.2g ]''\n', x_star(1),x_star(2),x_star(3) );

fprintf(1,'\nExact solutions were:      x = [ %2.2g %2.2g %2.2g ]'''  , x_ex(1,1),x_ex(2,1),x_ex(3,1) );
fprintf(1,'\n                           x = [ %2.2g %2.2g %2.2g ]'''  , x_ex(1,2),x_ex(2,2),x_ex(3,2) );
fprintf(1,'\nand the space generated by v = [ %2.2g %2.2g %2.2g ]''\n', x_set(1), x_set(2), x_set(3) );