MAP_LIST = { ...
  'Beale', ...
  'BiggsEXP6', ...
  'Box3', ...
  'BoxThreeDimensionalFunction', ...
  'BrownBadlyScaled', ...
  'Gauss', ...
  'GaussianFunction', ...
  'Han', ...
  'Helix', ...
  'Himmelblau', ...
  'JennrichAndSampson', ...
  'KowalikAndOsborne', ...
  'Leon', ...
  'PowellSingular', ...
  'Powell_bsf', ...
  'Rosenbrock', ...
  'TrivialQuadratic' ...
};
